### 1) Create 3X2 and 2X3 array.

In [5]:
arr1=np.array([[1,2],[3,4],[8,6]])
arr2=np.array([[1,5,3],[4,5,11]])

### 2) Initialize the array with random values.

In [6]:
arr1 = np.random.randint(6, size=(3,2))
arr2=np.random.randint(6, size=(2,3))
print(arr1)
print(arr2)

[[2 1]
 [4 5]
 [4 1]]
[[0 2 5]
 [0 2 1]]


### 3) Matrix multiplication of above 2 array.

In [7]:
ans=arr1.dot(arr2)
print(ans)

[[ 0  6 11]
 [ 0 18 25]
 [ 0 10 21]]


### 4 ) elementwise multiplication.

In [8]:
arr3=np.array([[7,8],[9,10],[11,12]])
np.multiply(arr1,arr3)

array([[14,  8],
       [36, 50],
       [44, 12]])

### 5) Find mean of a matrix.

In [9]:
arr1.mean()

2.8333333333333335

### 6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version.

In [12]:
from numpy import genfromtxt
data = genfromtxt('D:\Mywork\ML\mtcars.csv', delimiter=',')

In [13]:
data = np.delete(data,0, axis=0)
data = np.delete(data,0, axis=1)
data_mean_centric = data - np.mean(data, axis=0)
np.around(data_mean_centric, decimals=2)

array([[ 0.5],
       [-0.5]])

In [14]:
np.around(np.mean(data_mean_centric,axis=0),decimals=2)

array([0.])